import os

class Config:
    """
    Classe de configuração centralizada.
    Armazena constantes, chaves de API e mapeamentos de diretórios.
    """
    
    # Chave secreta para assinatura de sessões
    SECRET_KEY = os.environ.get('SECRET_KEY') or os.urandom(24)
    
    # Configurações de Upload
    MAX_CONTENT_LENGTH = 10 * 1024 * 1024 * 1024 
    UPLOAD_FOLDER = os.path.join(os.getcwd(), 'session_data')

    # Mapeamento de Escolas para IDs de Pastas do Google Drive
    FOLDER_MAP = {
        "ASSOCIAÇÃO JOÃO PAULO II": "1lceON-33pkAk-AN_K0a1-9-yXvk9uwqR",
        "CAIC - PROF FEBRONIO TANCREDO DE OLIVEIRA": "1CBew0EaMYRk1BD1yXwD2zeFgouj19Uv4",
        "CEI AMIGUINHOS DA COMUNIDADE": "1AnJQAWBC4A9jBqNyeMpstLXhZJBw6oEY",
        "CEI ANJINHO DA GUARDA": "1AtFxq441OK5z0B4HnRvZCDFQB0lWOYdw",
        "CEI APRENDER BRINCANDO": "1Jn2TJCRTdae05oyjzCAEAzHUBLpbSKpB",
        "CEI AQUARELA": "15dZQeBfGR9koDjBDiEAQUE-t-IkoCVCr",
        "CEI BOLINHAS DE SABÃO": "16UHzvm-fMEBmM02rlQX8xzpyHsRwmo_E",
        "CEI CAIC": "10bLdh8rqMN-C6PJq9qpS2wn6uSSIGduU",
        "CEI CAMINHO DO APRENDER": "1bLSgp6qkIhn0WKOksWQCIsaGXVzgI0_u",
        "CEI CAMINHO DA IMAGINAÇÃO": "10gHB-mejqYgP5QVGeFgxpb2u-rlNVMyH",
        "CEI CANARINHO": "1va-flnrPHXz94upF63VSSqxTFHkI8QVb",
        "CEI CHAPEUZINHO VERMELHO": "1-szFWrv_3jKFHAKLWm-l9BG75X_BAzod",
        "CEI CIRANDA COLORIDA": "1v7B2rZ_5k_OdO_h7nc_L87Bnd3uGCUUy",
        "CEI CONVIVER": "1VbuRny1r4cIVicttmhPUa_jTILOwaYsR",
        "CEI CRIANÇA FELIZ": "1Qq-zuhSBZqeYPbOviLooMr8zApU1pyD5",
        "CEI DONA MARICOTA": "1ZG2QPKWTE4uxRpbVOHTzD6DRZ_BszP37",
        "CEI ESPAÇO CRIATIVO": "1DT4hwv1lnkQDK1VU5nbHDKXYfGTR8qxj",
        "CEI ESTRELA DO MAR PROF REGINA CAETANA DA SILVEIRA": "1DZ-ssSakfdHXksHKMnmtKUDNIzO3arra",
        "CEI ESTRELINHA": "1BTYzQbLm3zdkdWcxMunWju7-PUhPgdVF",
        "CEI FLORZINHA AZUL": "1_TrZc5Nq2kMRtrnYUOaMXRLPqEZeOHB2",
        "CEI FORMIGUINHAS": "1QgCfK0lAt-3o3J5_WUoJn8jQ8xqLMfip",
        "CEI FILHOS DA TERRA": "1-2gOO2TnMN10xLWutDViqZmp-TrQpKVE",
        "CEI INOVAÇÃO": "104UWCNCrPRiodkiAVJ15fcHgLbfM73WN",
        "CEI INTERAÇÃO": "1eSgJqZ9dSbPlb4fnqRIkR8sg557sdQp0",
        "CEI JOSÉ MIGUEL FERREIRA": "1A3_MZvGYWejbqM_n9e218Yw5EKVo01nm",
        "CEI MUNDO ENCANTADO": "1ZJV9zJcmr3G-hbO0w3DDzMoFv6C2XJsR",
        "CEI MUNDO MÁGICO": "1a8zl1UfcuX4d23VLv0TDFG5cuJmcWVXI",
        "CEI MARIA DOS SANTOS SILVA": "1ttPZDyN8IhV9IdAGQdpUk8UdEcdmpYef",
        "CEI MARIA JOSÉ DE MEDEIROS": "1iLmmKNx6lCjSCxOxA8XdoXxV1MOpuNDa",
        "CEI NOVA ESPERANÇA": "13UaBcioA29p56VhiC5d7Admagmh9e2kp",
        "CEI NOVA GERAÇÃO": "1r-ApZx5VKADYLGRBOo2OJk7Z0gp-niwu",
        "CEI PADRE RÉUS": "1mqw91sslr5Ko4K4Cy5pE95BmsIQScykU",
        "CEI PARAÍSO DO AMOR": "1UkdML6aFX9h31j9aJWylywofDmeCndkX",
        "CEI PRIMEIROS PASSOS": "1sgqCIScyrMcHfQVcwBRONqe5-BFP2zrW",
        "CEI PROF ARGEMIRA DE FARIAS DA SILVEIRA": "1_YoLuJSw-Cc33h94wRBnV6rG9sZZWe1L",
        "CEI PROF AURORA DA SILVA LOPES": "1ayOfMuvhNzeJRtz1xGkFbEq8WTrvLkYw",
        "CEI PROF INÊS MARTA DA SILVA": "12tWNdKLkkA_DdC9COdjHu2aHbmg_Pmqf",
        "CEI PROF PAULO BRAULIO GOULART": "1xZ4VT3yaIXnGZ2sLJe33gwdjVSN_D1fk",
        "CEI REALIZAR": "1XjoBKDU0cp4AmCKq4YfR-L-MpeYmG6gZ",
        "CEI RODA VIVA": "1d-Yyp7dG77GcIfbfLl80kZ54dI8hQLjm",
        "CEI ROMEU E JULIETA": "1cDzd5FdGg96DzZA9uWSO5bytLhfqUMBR",
        "CEI SANTA MARTA": "1SRa-BloTjltMlTfMnIOxhk2APiXwyPD2",
        "CEI SÃO TOMÉ": "16lAIQuHMkWz_R_NRbZ517fntJWQrZMTl",
        "CEI SNOOPY": "1wO3zYTfszoJY2sWLWFX7vFxUO7VBZ8dl",
        "CEI ULISSES GUIMARÃES": "1a8NHkVW9CmZmiF4d4rJLJvkFGjfS7j4X",
        "CEI VALE VERDE PROF. MAURICIO SCHMITT": "1N52QSgfdy3vhEHE6UqWxT_qZ-qFyIPcZ",
        "CEI VIDA MELHOR": "14fAJX6Fm8wQgkgvhuy6sZRHF0B5857u0",
        "CEI VÓ LAURA": "1U7V-23QiyG7j4KHUJ0_jB4rw4-BnP0Cp",
        "CEI VOO LIVRE": "1dPGRQH9fjM52tD7pGAZ671JDkJkm532X",
        "CEI VOVÓ MARIA": "1T5TTN7uNDr17Zs2kIlj_DW0z_CnBipmt",
        "CEI VOVÓ DOLORES": "1J1NT1SrM1H4l32um4v-sIzdBwEppoPrJ",
        "EB ABÍLIO MANOEL DE ABREU": "1B1rc61ao6jGYc5lx8S5v2zG6Tcj7jAMK",
        "EB ANTONIETA SILVEIRA DE SOUZA": "17DzosmvTVTMJsCrwn-ZX9-45qMQhwIxW",
        "EB FREI DAMIÃO": "1zQx5U-zsOfSfmnTUo30Ffh1k7Qp2yzy8",
        "EB NERI BRASILIANO MARTINS": "1kIVVdS-qS-h7wPCkIpxEcUw8WgBbo656",
        "EB NOSSA SENHORA DE FÁTIMA": "1KYAyTdSVVjU9ZNh2J0l63eU6b1cLVvKB",
        "EB PROF FRANCISCA RAIMUNDA FARIAS DA COSTA": "19CPUW5k1dK2iY2t5WiohciA7GL7iagfq",
        "EB PROF LAURITA WAGNER DA SILVEIRA": "1H98U2UiW-2FEVPbsnUiKOGRS2dg5k1uq",
        "EB PROFª ADRIANA WEINGARTNER": "1e-rtvJqKFMedGXJlD9l-UkUE1pcFyjCl",
        "EB VIVIANE LAURITA DE QUADROS COELHO": "1EmA2TF4aRXZFiOtc1RPCCTa4nG7QqwA8",
        "EBM PROF MARA LUIZA VIEIRA LIBERATO": "1igrWoX699aboGZ86LGiivRRg-7fBul_T",
        "EBM PROF. OSMAR ANTÔNIO VIEIRA": "1oF0F0mnotfaEe72OPgQYETerJSGvv2pB",
        "EBM REINALDO WEINGARTNER": "1UpN4_iJ6pc6ETMDGhgEGPi2DAVL45-y5",
        "EI DO RINCÃO": "18-JqrK_DfuSvfTFpWgiAmEQUMtTCArw_",
        "ER ALBARDÃO": "14aZayeFnpD8qKhgqMNltltw_BFtGivqt",
        "ER BENTO JOSÉ DO NASCIMENTO": "1E2UE8ne44jaAlJ2LuBoZs-kaxDWwEioa",
        "ER DANIEL CARLOS WEINGARTNER": "12i7OyObNXdQLvtR6dTa7JEJfjk_9i7qr",
        "ER ISABEL BOTELHO DE PAULO": "1_vmcQugDurwQfSvAhqIVPeM4j4ILgGCm",
        "ER MANOEL DA SILVA": "1RVyCidQyRewBbk-s0H4-Lp1WyhSCh2Au",
        "ER OLGA CERINO": "14WYgP_R9I9CfKNshUkGYGXZS8dOFmyCf",
        "FUNDAÇÃO FÉ E ALEGRIA DO BRASIL": "1pKN8Ukf9fiInysN-r94z91XkI8z-mM5b",
        "GE EVANDA SUELLI JUTTEL MACHADO": "1cmyPQeZP3fF2BUS85Y8cx5CcA0jvGjvv",
        "GE GUILHERME WIETHORN FILHO": "1DR0o8J1DYkQLgigWTzjgDNgk54uVvvRz",
        "GE NAJLA CARONE GUEDERT": "1EJLUQoiiTpOw6QAbMBokUlyRjdUQLWaL",
        "GE PEQUENO PRÍNCIPE": "1v3pwUajWs28jRCqa6Hl0ruNqeac8gSxV",
        "GE PROF MARIA LUZIA DE SOUZA": "1Jii-YViEMEcP6kCtgNZ_dHACizLMuNQU",
        "GE TEREZINHA MARIA ESPÍNDOLA MARTINS": "1qOpWETmx8J0Q3R6QCfbKmTWGDpDfyCCB"
    }